AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy AWX (Ansible Tower open source) on AWS

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m5.large
    ConstraintDescription: must be a valid EC2 instance type.

Resources:
  AWXInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI
      SecurityGroups:
        - !Ref AWXSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 python3-pip
          pip3 install docker
          amazon-linux-extras install epel -y
          yum install -y git
          git clone https://github.com/ansible/awx.git
          cd awx/installer
          ansible-playbook -i inventory install.yml

  AWXSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, HTTP, and HTTPS access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  AWXURL:
    Description: URL of the AWX instance
    Value: !Sub "http://${AWXInstance.PublicDnsName}"

