---
- name: Deploy CloudFormation templates to AWS
  tasks:
    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Configure AWS CLI
      shell: aws configure set aws_access_key_id {{ aws_access_key_id }} && aws configure set aws_secret_access_key {{ aws_secret_access_key }} && aws configure set default.region {{ aws_region }}

    - name: Create CloudFormation stack
      shell: aws cloudformation create-stack --stack-name {{ stack_name }} --template-body file://{{ template_file }} --parameters file://{{ parameters_file }} --capabilities CAPABILITY_IAM

    - name: Wait for stack creation to complete
      shell: aws cloudformation wait stack-create-complete --stack-name {{ stack_name }}

    - name: Get stack outputs
      shell: aws cloudformation describe-stacks --stack-name {{ stack_name }} --query 'Stacks[0].Outputs' --output json
      register: stack_outputs

    - name: Print stack outputs
      debug:
        var: stack_outputs
