AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Athena Data Catalog with Glue Crawler

Parameters:
  AthenaBucketName:
    Description: Name for the S3 bucket used by Athena
    Type: String

Resources:
  AthenaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AthenaBucketName
      AccessControl: BucketOwnerFullControl

  AthenaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AthenaBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action: s3:GetBucketLocation
            Resource: !Sub arn:aws:s3:::${AthenaBucket}
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action: s3:ListBucket
            Resource: !Sub arn:aws:s3:::${AthenaBucket}
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${AthenaBucket}/*

  AthenaQueryExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AthenaQueryExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AthenaQueryExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:StopQueryExecution
                Resource: '*'

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: "my_athena_database"

  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "my_table"
        Description: "My Glue Table"
        Parameters:
          has_encrypted_data: false
        StorageDescriptor:
          Columns:
            - Name: "column1"
              Type: "string"
            - Name: "column2"
              Type: "int"
          Location: !Sub "s3://${AthenaBucket}/data"
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.serde2.OpenCSVSerde"
            Parameters:
              separatorChar: ","
              quoteChar: "\""
              escapeChar: "\\"
              serialization.format: "1"
        TableType: "EXTERNAL_TABLE"

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub "s3://${AthenaBucket}/data"
      Schedule: "cron(0 0 * * ? *)"

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueCrawlerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:ListBucket
                Resource: "*"

Outputs:
  AthenaBucketOutput:
    Description: S3 bucket for Athena
    Value: !Ref AthenaBucket
  AthenaQueryExecutionRoleOutput:
    Description: IAM role for Athena query execution
    Value: !Ref AthenaQueryExecutionRole

