---
# Gather information about all VPCs
- amazon.aws.ec2_vpc_net_info:

- name: start an instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    region: "{{ ansible_ec2_placement_region }}"
    instance_type: "{{ instance_type }}"
    network:
      assign_public_ip: true
    image_id: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ subnet_id }}"
    security_group: "{{ security_group_id }}"
  register: ec2_instance

- name: Wait for known hosts
  ansible.builtin.pause:
    minutes: 1

- name: Print Bastion EC2 instance details
  debug:
    var: ec2_instance.instances[0]
