AWSTemplateFormatVersion: '2010-09-09'
Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: MyKinesisStream
      ShardCount: 1
      RetentionPeriodHours: 24
      StreamEncryption:
        EncryptionType: KMS
        KeyId: <your-kms-key-id>

